<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-G790OGBU" name="Test" tests="7" failures="1" timestamp="23 Apr 2025 11:25:23 GMT" time="6.175" errors="0">
  <testcase name="getUrl" time="0.014" classname="com.menumitratCommonAPITestScript.loginTestScript"/>
  <testcase name="verifyloginUsingValidInputData" time="3.648" classname="com.menumitratCommonAPITestScript.loginTestScript">
    <failure type="com.menumitra.utilityclass.customException" message="An error occurred during login verification">
      <![CDATA[com.menumitra.utilityclass.customException: An error occurred during login verification
	at com.menumitratCommonAPITestScript.loginTestScript.verifyloginUsingValidInputData(loginTestScript.java:175)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifyloginUsingValidInputData -->
  <testcase name="getOwnerUrl" time="0.002" classname="com.menumitraOwnerAPITestScript.OwnerverifyOtpTestScript"/>
  <testcase name="verifyOTPAPiUsingValidInputData" time="0.325" classname="com.menumitraOwnerAPITestScript.OwnerverifyOtpTestScript"/>
  <testcase name="getResendOTPURL" time="0.001" classname="com.menumitratCommonAPITestScript.ResendOTPTestScript"/>
  <testcase name="verifyRessendOTPUSingPositiveInputData" time="0.186" classname="com.menumitratCommonAPITestScript.ResendOTPTestScript"/>
  <testcase name="createStaff" time="0.001" classname="com.menumitratCommonAPITestScript.StaffCreateTestScript"/>
</testsuite> <!-- Test -->
