<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-G790OGBU" name="com.menumitratCommonAPITestScript.SupplierCreateTestScript" tests="4" failures="0" timestamp="6 May 2025 10:28:37 GMT" time="1.282" errors="1">
  <testcase name="createSupplier" time="0.578" classname="com.menumitratCommonAPITestScript.SupplierCreateTestScript">
    <error type="com.menumitra.utilityclass.customException" message="Test execution failed: Status code validation failed - Expected: 200, Actual: 400">
      <![CDATA[com.menumitra.utilityclass.customException: Test execution failed: Status code validation failed - Expected: 200, Actual: 400
	at com.menumitratCommonAPITestScript.SupplierCreateTestScript.createSupplier(SupplierCreateTestScript.java:316)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- createSupplier -->
  <testcase name="supplierCreateNegativeTest" time="0.220" classname="com.menumitratCommonAPITestScript.SupplierCreateTestScript"/>
  <testcase name="supplierCreateNegativeTest" time="0.314" classname="com.menumitratCommonAPITestScript.SupplierCreateTestScript"/>
  <testcase name="supplierCreateNegativeTest" time="0.170" classname="com.menumitratCommonAPITestScript.SupplierCreateTestScript"/>
</testsuite> <!-- com.menumitratCommonAPITestScript.SupplierCreateTestScript -->
